//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion
    {
        public long Expr1 { get; set; }
        public long cat_metodo { get; set; }
        public string cat_metodo_descrip { get; set; }
        public long metodo_id { get; set; }
        public long metodo_evaluacion { get; set; }
        public long metodo_pac_id { get; set; }
    }
}
