//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion_resultado
    {
        public long evaluacion_id { get; set; }
        public long evaluacion_pac_id { get; set; }
        public long evaluacion_metodo { get; set; }
        public string evaluacion_resultado1 { get; set; }
    
        public virtual metodo_evaluacion metodo_evaluacion { get; set; }
    }
}
