//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hojausomultiple
    {
        public long paciente_id { get; set; }
        public long paciente_usuario { get; set; }
        public string paciente_nombre { get; set; }
        public Nullable<long> paciente_sexo { get; set; }
        public int paciente_edad { get; set; }
        public string paciente_edo_nac { get; set; }
        public string paciente_mun_nac { get; set; }
        public Nullable<System.DateTime> paciente_fec_nac { get; set; }
        public Nullable<int> paciente_edo_civil { get; set; }
        public Nullable<int> paciente_estatus { get; set; }
        public string paciente_direccion { get; set; }
        public string paciente_ocupacion { get; set; }
        public Nullable<int> paciente_escolaridad { get; set; }
        public Nullable<System.DateTime> paciente_fec_ing { get; set; }
        public string paciente_telefono { get; set; }
        public Nullable<int> paciente_modalidad { get; set; }
        public long usuario_id { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_direccion { get; set; }
        public string usuario_cel { get; set; }
        public string usuario_telcsa { get; set; }
        public string usuario_correo { get; set; }
        public Nullable<int> usuario_tipo { get; set; }
        public Nullable<System.DateTime> usuario_fecha_ing { get; set; }
        public string usuario_password { get; set; }
        public string usuario_cedula { get; set; }
        public long Expr1 { get; set; }
        public string sexo_descrip { get; set; }
        public string edocivil_descrip { get; set; }
        public string modalidad_descrip { get; set; }
    }
}
