//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infogeneral
    {
        public long paciente_id { get; set; }
        public long paciente_usuario { get; set; }
        public string paciente_nombre { get; set; }
        public string sexo_descrip { get; set; }
        public int paciente_edad { get; set; }
        public string desc_edo { get; set; }
        public string desc_mun { get; set; }
        public Nullable<System.DateTime> paciente_fec_nac { get; set; }
        public string edocivil_descrip { get; set; }
        public string estatus_descrip { get; set; }
        public string paciente_direccion { get; set; }
        public string paciente_ocupacion { get; set; }
        public string escolar_descrip { get; set; }
        public Nullable<System.DateTime> paciente_fec_ing { get; set; }
        public string paciente_telefono { get; set; }
        public string paciente_telefono_eme { get; set; }
        public string modalidad_descrip { get; set; }
        public string estado_res { get; set; }
        public string municipio_res { get; set; }
    }
}
