//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_recuerdos_tempranos
    {
        public long pac_recuerdos_id { get; set; }
        public long pac_recuerdos_pac_id { get; set; }
        public string pac_recuerdos_temp { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
