//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_datos_maritales
    {
        public long pac_maritales_id { get; set; }
        public long pac_maritales_pac_id { get; set; }
        public string pac_maritales_noviazgo { get; set; }
        public string pac_maritales_expnoviazgo { get; set; }
        public string pac_maritales_desc_conyuge { get; set; }
        public string pac_maritales_eventos { get; set; }
        public string pac_maritales_numhijos { get; set; }
        public string pac_maritales_interaccion { get; set; }
        public string pac_maritales_familia { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
