//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_situacion_act
    {
        public long pac_situacion_id { get; set; }
        public long pac_situacion_pac_id { get; set; }
        public string pac_situacion_dia { get; set; }
        public string pac_situacion_esp { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
