//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_desarrollo_sexual
    {
        public long pac_desarrollo_id { get; set; }
        public long pac_desarrollo_pac_id { get; set; }
        public string pac_desarrollo_nociones { get; set; }
        public string pac_desarrollo_contacto { get; set; }
        public string pac_desarrollo_interes { get; set; }
        public string pac_desarrollo_fantasias { get; set; }
        public string pac_desarrollo_homosex { get; set; }
        public string pac_desarrollo_relaciones { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
