//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_psicoterapia
    {
        public long pac_psico_id { get; set; }
        public long pac_psico_pac_id { get; set; }
        public string pac_psico_desc { get; set; }
        public string pac_psico_texto { get; set; }
        public Nullable<System.DateTime> pac_psico_fecha { get; set; }
        public string pac_psico_intervencion { get; set; }
        public string pac_psico_tecnicas { get; set; }
        public string pac_psico_resultados { get; set; }
        public string pac_psico_recomenda { get; set; }
        public string pac_psico_observaciones { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
