//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_estado_mental
    {
        public long pac_estado_id { get; set; }
        public long pac_estado_pac_id { get; set; }
        public string pac_estado_conciencia { get; set; }
        public string pac_estado_orientacion { get; set; }
        public string pac_estadoafectividad { get; set; }
        public string pac_estado_asociaciones { get; set; }
        public string pac_estado_pensamiento { get; set; }
        public string pac_estado_percepcion { get; set; }
        public string pac_estado_funcionamiento { get; set; }
        public string pac_estado_juicio { get; set; }
        public string pac_estado_insight { get; set; }
        public string pac_estado_madurez { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
