//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_desc_simismo
    {
        public long pac_simismo_id { get; set; }
        public long pac_simismo_pac_id { get; set; }
        public string pac_simismo_comoseve { get; set; }
        public string pac_simismo_comocree { get; set; }
        public string pac_simismo_preocupaciones { get; set; }
        public string pac_simismo_metas { get; set; }
        public string pac_simismo_gustaria { get; set; }
        public string pac_simismo_crisis { get; set; }
        public string pac_simismo_triunfo_frac { get; set; }
        public string pac_simismo_siente_problem { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
