//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_ajustes_sociales
    {
        public long pac_ajustes_id { get; set; }
        public long pac_ajustes_pac_id { get; set; }
        public string pac_ajustes_relacionesint { get; set; }
        public string pac_ajustes_amistades { get; set; }
        public string pac_ajustes_sentir { get; set; }
        public string pac_ajustes_novias { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
