//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_descrip
    {
        public long pac_desc_id { get; set; }
        public long pac_paciente_id { get; set; }
        public string pac_desc_aspectos { get; set; }
        public string pac_desc_vestimenta { get; set; }
        public string pac_desc_porte { get; set; }
        public string pac_desc_movimientos { get; set; }
        public string pac_desc_afecto { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
