//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_consulta
    {
        public long pac_cons_id { get; set; }
        public long pac_cons_pac_id { get; set; }
        public string pac_cons_problema { get; set; }
        public string pac_cons_historia { get; set; }
        public string pac_cons_referencia { get; set; }
        public string pac_cons_experiencia { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
