//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_constelacion_fam
    {
        public long pac_conste_id { get; set; }
        public long pac_conste_paciene_id { get; set; }
        public string pac_conste_texto { get; set; }
        public string pac_conste_antecedentes { get; set; }
        public string pac_conste_desc_padre_madre { get; set; }
        public string pac_conste_hermanos { get; set; }
        public string pac_conste_rivalidades { get; set; }
        public string pac_conste_papel_fam { get; set; }
        public string pac_conste_uniones { get; set; }
        public string pac_conste_normas { get; set; }
        public string pac_conste_cambios { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
