//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_record_trabajo
    {
        public long pac_record_id { get; set; }
        public long pac_record_pac_id { get; set; }
        public string pac_record_trabajos { get; set; }
        public string pac_record_sueldo { get; set; }
        public string pac_record_relacion { get; set; }
        public string pac_record_siente { get; set; }
    
        public virtual pacientes pacientes { get; set; }
    }
}
