//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientes
    {
        public pacientes()
        {
            this.pac_consulta = new HashSet<pac_consulta>();
            this.pac_descrip = new HashSet<pac_descrip>();
            this.pac_situacion_act = new HashSet<pac_situacion_act>();
            this.pac_ajustes_sociales = new HashSet<pac_ajustes_sociales>();
            this.pac_constelacion_fam = new HashSet<pac_constelacion_fam>();
            this.pac_datos_maritales = new HashSet<pac_datos_maritales>();
            this.pac_desarrollo_sexual = new HashSet<pac_desarrollo_sexual>();
            this.pac_desc_simismo = new HashSet<pac_desc_simismo>();
            this.pac_diversion_intereses = new HashSet<pac_diversion_intereses>();
            this.pac_escolaridad = new HashSet<pac_escolaridad>();
            this.pac_estado_mental = new HashSet<pac_estado_mental>();
            this.pac_historia_per = new HashSet<pac_historia_per>();
            this.pac_psicoterapia = new HashSet<pac_psicoterapia>();
            this.pac_record_trabajo = new HashSet<pac_record_trabajo>();
            this.pac_recuerdos_tempranos = new HashSet<pac_recuerdos_tempranos>();
            this.pac_diagnostico = new HashSet<pac_diagnostico>();
        }
    
        public long paciente_id { get; set; }
        public long paciente_usuario { get; set; }
        public string paciente_nombre { get; set; }
        public Nullable<long> paciente_sexo { get; set; }
        public int paciente_edad { get; set; }
        public string paciente_edo_nac { get; set; }
        public string paciente_mun_nac { get; set; }
        public Nullable<System.DateTime> paciente_fec_nac { get; set; }
        public Nullable<int> paciente_edo_civil { get; set; }
        public Nullable<int> paciente_estatus { get; set; }
        public string paciente_direccion { get; set; }
        public string paciente_ocupacion { get; set; }
        public Nullable<int> paciente_escolaridad { get; set; }
        public Nullable<System.DateTime> paciente_fec_ing { get; set; }
        public string paciente_telefono { get; set; }
        public Nullable<int> paciente_modalidad { get; set; }
        public string paciente_edo_res { get; set; }
        public string paciente_mun_res { get; set; }
        public string paciente_telefono_eme { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<pac_consulta> pac_consulta { get; set; }
        public virtual ICollection<pac_descrip> pac_descrip { get; set; }
        public virtual ICollection<pac_situacion_act> pac_situacion_act { get; set; }
        public virtual ICollection<pac_ajustes_sociales> pac_ajustes_sociales { get; set; }
        public virtual ICollection<pac_constelacion_fam> pac_constelacion_fam { get; set; }
        public virtual ICollection<pac_datos_maritales> pac_datos_maritales { get; set; }
        public virtual ICollection<pac_desarrollo_sexual> pac_desarrollo_sexual { get; set; }
        public virtual ICollection<pac_desc_simismo> pac_desc_simismo { get; set; }
        public virtual ICollection<pac_diversion_intereses> pac_diversion_intereses { get; set; }
        public virtual ICollection<pac_escolaridad> pac_escolaridad { get; set; }
        public virtual ICollection<pac_estado_mental> pac_estado_mental { get; set; }
        public virtual ICollection<pac_historia_per> pac_historia_per { get; set; }
        public virtual ICollection<pac_psicoterapia> pac_psicoterapia { get; set; }
        public virtual ICollection<pac_record_trabajo> pac_record_trabajo { get; set; }
        public virtual ICollection<pac_recuerdos_tempranos> pac_recuerdos_tempranos { get; set; }
        public virtual ICollection<pac_diagnostico> pac_diagnostico { get; set; }
    }
}
