//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.colegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.pacientes = new HashSet<pacientes>();
            this.pac_constelacion_fam = new HashSet<pac_constelacion_fam>();
        }
    
        public long usuario_id { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_direccion { get; set; }
        public string usuario_cel { get; set; }
        public string usuario_telcsa { get; set; }
        public string usuario_correo { get; set; }
        public Nullable<int> usuario_tipo { get; set; }
        public Nullable<System.DateTime> usuario_fecha_ing { get; set; }
        public string usuario_password { get; set; }
        public string usuario_cedula { get; set; }
    
        public virtual ICollection<pacientes> pacientes { get; set; }
        public virtual ICollection<pac_constelacion_fam> pac_constelacion_fam { get; set; }
    }
}
